### ISSUE TITLE
The :jvm-opts extracted should not be placed at the top level of deps.edn map

### ISSUE THREAD

**Issue by zerg000000** [hagmonk/depify#1]
Thanks for your tool! I recently try to convert my project.clj to deps.edn.

I found your depify did it quite nice! but when I try to launch the repl using the deps.edn. I found the :jvm-opts did not used by repl. After some research, tool.deps did not use the top level :jvm-opts.

don't know it is a tool.deps issue, or the extracted jvm-opts should be placed in some aliases.

**Comment by hagmonk** [comment]
You're 100% right, perhaps this behavior changed in tools.deps at some point, or perhaps I just had it wrong all along. I'll get it fixed.

**Comment by hagmonk** [comment]
Should be fixed now! Give it another try.

**Comment by hagmonk** [comment]
@zerg000000 let me know if things look good now, I'm pretty confident it's resolved. If I don't hear back in a few days I'll go ahead and close the issue.

**Comment by zerg000000** [comment]
Tested. Look good,the :jvm-opts problem has been resolved. very similar to my hand-crafted deps.edn. I think we can close this issue.

**Comment by hagmonk** [comment]
Thanks!
