### ISSUE TITLE
Allow input via stdin

### ISSUE THREAD

**Issue by darwin** [hagmonk/depify#2]
It would be great to able to feed depify with `lein pprint` output, e.g.

```
lein pprint | clj -A:depify
```

This would be useful for people who need to:
* [evaluate code in project.clj](https://github.com/binaryage/cljs-devtools/blob/7ace48cf25b89e3d3c37d99b623fa274a5d45c0f/project.clj#L13) 
* or extract dependencies from specific [lein profiles](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md), for example:
```
lein with-profile +my-profile pprint | clj -A:depify
```
* or preprocess project.clj via some other tool

FYI, here is an example how to implement optional reading from stdin:
https://github.com/xsc/lein-ancient/commit/9c973ce589f09c1ef026a92d112e5ad74911e881

**Comment by hagmonk** [comment]
Awesome, I had always been interested in how to detect stdin availability – I can make this change.

**Comment by hagmonk** [comment]
@darwin fix has been pushed, let me know if this works for you!

**Comment by darwin** [comment]
Thanks, but it does not work. You assume that `lein pprint` outputs `project.clj`, but it produces a map (EDN) with evaluated project content. Something similar to your `read-prj` output.

This is an example of cljs-devtools's project.clj output from lein-pprint:
https://gist.github.com/darwin/4a153dfc46aec48abdef3891ab6c0281

I think you have two options:
1) on stdin always expect this "evaluated" map
2) do some detection, e.g. detect if `defproject` is present and if not, assume map, or something similar

**Comment by darwin** [comment]
Thinking about it more. The heuristics could be:

1. if I'm getting a map use it as evaluated project
2. if I'm getting a list of maps, merge them left-to-right and use it as evaluated project
3. in other case assume project.clj source

**Comment by hagmonk** [comment]
Hah! Yeah I totally assumed it would output a project.clj form … such a strong assumption I didn't even bother running `lein pprint`. I'll revisit this. It looks like the pprint form is relatively close to what I build with read-prj, so this shouldn't be too hard.

Just out of interest, what is the use case for supporting a sequence of maps?

**Comment by darwin** [comment]
It is not important. Just more flexible if someone wanted to provide multiple projects and merge them. Actually `list of maps` wasn't really good description. I should have said:

1. if I'm getting a single form which is a map, use it as evaluated project
2. if I'm getting multiple forms which are all maps, merge them first and then use it as evaluated project

So it collapses to single case 2.

This would be modelled after lein-pprint feature. Look at last paragraph of https://github.com/xsc/lein-ancient/commit/9c973ce589f09c1ef026a92d112e5ad74911e881. 

lein-pprint can select submaps from the main map. If you specify multiple paths it will give you multiple forms on output. Try:

`lein pprint :dependencies`
`lein pprint :dependencies :plugins`

**Comment by hagmonk** [comment]
Got it. By the way, I was wanting to bulk import some deps from someone else's project into my current project, and suddenly found a use for the changes I made, even though they went in the wrong direction at first:

`curl -L -o - "https://raw.githubusercontent.com/metasoarous/oz/master/project.clj" | clj -A:depify` 

I'll get the `lein pprint` format done later on today, it shouldn't be too hard. I agree supporting the format from `lein pprint` with multiple args is worthwhile, it's an elegant way for someone to be selective about what parts of their project.clj should be converted.

**Comment by hagmonk** [comment]
Looks like `lein pprint :dependencies` extracts only the value for that key from the `defproject` form, which for instance means we could never distinguish `:dependencies` from `:plugins`. As a compromise, I'm going to add a pattern match for "sequence of things that look like dependencies", but I don't think it's worth the engineering time to pattern match and disambiguate other keys. This at least enables people to extra purely just the dependencies.
